server:
  port: 8888

spring:
  datasource:
    username: "root"
    password:
    url: "jdbc:mysql://localhost:3306/music?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  type-aliases-package: com.xiao.music.pojo
  mapper-locations: classpath:mapper/*.xml
